### ISSUE TITLE
Mobx observable not working in release build

### ISSUE THREAD

**Issue by Lelelo1** [shirakaba/react-nativescript#46]
I have used the state management tool MobX in my app and everything has worked in debug - but in release however - MobX observables has stopped working and no more triggering render.

Usage, where I have button:

```
<$Button ref={this.recordButtonRef} text={"Personuppgifter"} onTap={() => {
    console.log("settin: " + !FormViewModel.get().isHidden);
    FormViewModel.get().isHidden = !FormViewModel.get().isHidden;
}}
/>
```
Where the FormViewModel is synonymous to a "Store":

```
@observable
isHidden = true;
```

And a form is rendered depending on the value of `isHidden`:

```
renderForm() {
    return FormViewModel.get().isHidden ? null : ( 
        <$CardView
            forwardedRef={this.cardViewRef}
            margin={10}
            borderWidth={2} 
            shadowOffsetHeight={2}
            shadowOffsetWidth={1}
            className={"cardStyle"}
         >
         <Form ref={this.formRef} />
     </$CardView>
            
        );
    }
```

Note that most of the app was developed without `rns-reactify` and those parts has also stopped functioning where they are using mobx observable.  I am never calling `setState` in my app - using mobx instead.

---
My dependencies are the following:

> "dependencies": {
    "@nstudio/nativescript-cardview": "^1.0.0",
    "@nstudio/nativescript-checkbox": "^1.0.0",
    "mobx": "^5.13.0",
    "mobx-react": "^6.1.3",
    "nativescript-carousel": "^6.1.0",
    "nativescript-cfalert-dialog": "^1.0.15",
    "nativescript-contacts": "^1.6.2",
    "nativescript-email": "^1.5.5",
    "nativescript-floatingactionbutton": "^5.1.0",
    "nativescript-iqkeyboardmanager": "^1.5.1",
    "nativescript-theme-core": "^1.0.6",
    "nativescript-toasty": "^2.0.1",
    "react": "^16.9.0",
    "react-nativescript": "^0.12.0",
    "rns-reactify": "git+https://github.com/Lelelo1/rns-reactify.git",
    "tns-core-modules": "6.0.1",
    "tns-platform-declarations": "^6.0.6"
  },
  "devDependencies": {
    "@babel/core": "^7.5.0",
    "@babel/plugin-proposal-class-properties": "^7.5.0",
    "@babel/preset-react": "^7.0.0",
    "@types/react": "^16.9.2",
    "awesome-typescript-loader": "^5.2.1",
    "babel-loader": "^8.0.6",
    "fork-ts-checker-webpack-plugin": "^1.3.7",
    "nativescript-dev-webpack": "1.0.1",
    "react-nativescript-hot-loader": "git+https://github.com/shirakaba/react-nativescript-hot-loader.git",
    "typescript": "3.4.5"
  },

**Comment by shirakaba** [comment]
This is a complete guess, but try updating to `react-nativescript` `v0.15.0` (you can ignore the complaint that no peer of `tns-core-modules@^6.2.1` has been provided, as I'm not actually using any v6.2.x features in that release). I'm just thinking that it could be that `mobx-react` relies on hooks, and that updating to the new hooks-friendly RNS may help that.

I've never used MobX, so I'd need to investigate what `@observable` does to understand how RNS might be conflicting with it.

The very strange thing is that it only affects release builds :/

I'm not doing much different in release mode to my knowledge (just turning on minification, etc.), but maybe React Reconciler or MobX-React behaves differently in release mode, for example. 

Is your project closed-source? Feeling a bit low on details here (though I appreciate that it's a strange issue), so can't give many suggestions.

**Comment by Lelelo1** [comment]
I do get errors after updating react-nativescript. The `TextBase.d.ts` (only) seem to have changed nativescript import paths to the newer ones:. Inside TextBase.d.ts:

![Screenshot 2019-11-19 at 16 00 36](https://user-images.githubusercontent.com/42244983/69157779-bd6c4780-0ae5-11ea-88e6-d0b4966c9a79.png)

I don't know how though looking in [TextBase](https://github.com/shirakaba/react-nativescript/blob/master/react-nativescript/src/components/TextBase.ts) component. It is required to resolve all errors to be able to produce a release build.

**Comment by shirakaba** [comment]
Oh well, looks like you'll need to update to NativeScript v6.2.x to clear that error :( I found it to be a painless and easy process for my RNS apps, however. The command to do that is simply:

```sh
# In the root of your project
tns update
```

**Comment by Lelelo1** [comment]
I will just have to update all imports I have made in the project. It was not until late I started to import from `ElementRegistry`

**Comment by shirakaba** [comment]
Importing from `ElementRegistry` should actually still work for now (although I'll be removing them in a future release, as `@nativesript/core` serves the same purpose, only more elegantly and thoroughly).

**Comment by Lelelo1** [comment]
I now get the following errors after when `tns run android`
> ERROR in [at-loader] ./node_modules/mobx/lib/api/flow.d.ts:8:83 
    TS2315: Type 'Generator' is not generic.
ERROR in [at-loader] ./node_modules/mobx/lib/api/flow.d.ts:8:108 
    TS2304: Cannot find name 'AsyncGenerator'.
ERROR in /Users/hemma/Projects/avfallshamtning/node_modules/mobx/lib/api/flow.d.ts
ERROR in /Users/hemma/Projects/avfallshamtning/node_modules/mobx/lib/api/flow.d.ts(8,83):
TS2315: Type 'Generator' is not generic.
ERROR in /Users/hemma/Projects/avfallshamtning/node_modules/mobx/lib/api/flow.d.ts
ERROR in /Users/hemma/Projects/avfallshamtning/node_modules/mobx/lib/api/flow.d.ts(8,108):

And the mobx observable now seem broken in debug on android. But it functions on iOS.

**Comment by shirakaba** [comment]
Thanks for providing the source. I’ll try to determine what the problem is if I have time tonight.

**Comment by shirakaba** [comment]
But for now, my only thoughts are:

* Need to clean the Android debut build
* Maybe Awesome TypeScript Loader needs to be updated to use a newer TypeScript version or something...

**Comment by Lelelo1** [comment]
It was `tns update --markingMode` needed when running on android emulator (which is api 28) (while android phone is api 23). This could very well also make it work on both phone and emulator with my release apk from Nativescript sidekick.

**Comment by shirakaba** [comment]
Ah, so do you mean that that resolved the problem with `at-loader`?

**Comment by Lelelo1** [comment]
> Ah, so do you mean that that resolved the problem with at-loader

I don't know. There was simply a big yellow warning telling me to  `tns update --markingMode` after I updated to `NativeScript v6.2.x `. Now I have to get rid of those errors inside mobx.

**Comment by shirakaba** [comment]
Okay, keep me updated on any problems you might be stumped by.

**Comment by Lelelo1** [comment]
I am still experiencing the problem with a newly made release apk. I have realised it is by pressing one button that:
* does not show it's content like it does in debug
* causes other things relaying on mobx observables to fail.

The other things relaying on mobx is in fact working as long as the particular button is not pressed. The code of the button is what I presented when opening the issue. So I believe the fault is in fact in [rns-reactify](https://github.com/Lelelo1/rns-reactify)

**Comment by Lelelo1** [comment]
I removed `rns-reactify` and it started working.

Which means I am instantiating `CardView` outside jsx - and handling show and hide (add remove) in componentDidMount. Like I had done in the other parts of the app.

```
<$ContentView ref={this.formContainer}>
    <Form ref={this.formRef} />
</$ContentView>
```
