### ISSUE TITLE
Investigate whether release build and publishing works

### ISSUE THREAD

**Issue by shirakaba** [shirakaba/react-nativescript#47]
See: https://github.com/NativeScript/nativescript-cli/issues/4944#issuecomment-520006733

**Comment by Lelelo1** [comment]
The sample project looks more healthy to me than my own project where I had to move `info.plist`. Opening xcodeworkspace in that project:
![Screenshot 2019-12-27 at 15 54 38](https://user-images.githubusercontent.com/42244983/71521460-328b2380-28c1-11ea-85c6-a3e949126d17.png)

... there are duplicate resources. It does not seem to the case with the sample project.

**Comment by shirakaba** [comment]
I published an app ([NS:IDE](https://github.com/shirakaba/nside)) based on the latest RNS template; release build and publishing went fine.
