### ISSUE TITLE
JS ERROR ReferenceError: Can't find variable: process

### ISSUE THREAD

**Issue by spacesuitdiver** [shirakaba/react-nativescript#51]
With a vanilla install I end up getting this when running `tns preview` I vaguely recall mention about react not guarding process somewhere, maybe that was redux. 

```
2020-04-11 13:29:05.267 nsplaydev[26749:9709575] *** Terminating app due to uncaught exception 'NativeScript encountered a fatal error: ReferenceError: Can't find variable: process
 at 
anonymous(file:///app/tns_modules/react-hot-loader/index.js:3:12)
```

**Comment by shirakaba** [comment]
This is due to NativeScript Preview. Now tracked in: https://github.com/NativeScript/nativescript-cli/issues/5295

**Comment by shirakaba** [comment]
As of v1, React NativeScript uses React Fast Refresh rather than React Hot Loader. Preview will be updated to use RNS v1 sometime soon (I've made the PRs and nStudio will try to deploy them sometime soon).

**Comment by spacesuitdiver** [comment]
Thanks Jamie. Let me know when you get it merged in and I’ll give it a try.
