### ISSUE TITLE
<$Span> should accept a text node similar to <$Label>

### ISSUE THREAD

**Issue by spacesuitdiver** [shirakaba/react-nativescript#53]
<$Span> should accept a text node similar to <$Label> considering they both use a text prop.

**Comment by shirakaba** [comment]
Good point! Does $Span render nothing if a text node is provided? I thought the renderer would automatically handle text node addition for any element extending TextBase. But maybe it doesn’t extend TextBase at all.

**Comment by spacesuitdiver** [comment]
Yea here's the markup vs. rndebugger.

![image](https://user-images.githubusercontent.com/2807897/79075115-5af32e00-7cb6-11ea-8ed0-901e5ff548df.png)

![image](https://user-images.githubusercontent.com/2807897/79075107-52025c80-7cb6-11ea-95c9-418154d2c88b.png)

**Comment by spacesuitdiver** [comment]
Side note, it's interesting that those `<$Label>` tags get `<class_1>`.

**Comment by Lelelo1** [comment]
**[`Span`](https://docs.nativescript.org/api-reference/classes/__nativescript_core_.span) is actually inheriting `ViewBase`, while [Label](https://docs.nativescript.org/api-reference/classes/_ui_label_.label) inherits `TextBase` in nativescript core.** [RNS Span](https://github.com/shirakaba/react-nativescript/blob/master/react-nativescript/src/components/Span.ts) has mimicked it extending `RCTViewBase`. It could be more intuitive to be able to put text between the tags on Span as well.

Why Span inherits ViewBase could be due to the **ability to display glyphs**:
```
<$Button
    ref={this.button0Ref}
    onTap={() => {
        console.log("hello icon button world)
    }}
 >
    <$FormattedString
        backgroundColor={new Color("transparent")}
    >
        <$Span text={content0.glyph} className={content0.css} />
        <$Span text={this._getText(content0)} />
    </$FormattedString>
</$Button>
```

Where content0 is instance of:
```
export class Content {
    text: string;
    css: string;
    glyph: string;
    // onTap: () => void;
}
```
More on using Span to to have icons: https://stackoverflow.com/questions/57976473/unable-to-use-font-icon-in-nativescript

**Comment by shirakaba** [comment]
@Lelelo1 Thanks for digging that up. That makes sense.

@spacesuitdiver I've added support for entering text nodes as children into `<$Span>` elements now, in React NativeScript `v0.24.0`:

```sh
npm install --save react-nativescript
```

This feature release also removes a redundant call to notifyPropertyChange, which may improve text relayout.

---

Something related will need revisiting in future, as I've stumbled upon a limitation of React: parent context is only conveyed, in [`HostConfig.getChildHostContext()`](https://github.com/shirakaba/react-nativescript/blob/b8b8d8557f220f532277dca6133729536bc48886/react-nativescript/src/client/HostConfig.ts#L176), by the name of the primitive element; the Host Config doesn't provide the parent instance itself, so you can't perform `instanceof` checks at this moment in the rendering lifecycle. Thus, we can't ever say "this child is an ancestor of any arbitrary class extending TextBase".

At the moment, I use this ancestor context to throw an error if ever a user tries to make a text node under the wrong element. But in future, I may have to just allow text nodes anywhere and make the Host Config complain at a later point, e.g. property setting, as in [`setTextContent()`](https://github.com/shirakaba/react-nativescript/blob/b8b8d8557f220f532277dca6133729536bc48886/react-nativescript/src/client/ReactNativeScriptComponent.ts#L53).

Until then, non-core components extending TextBase (e.g. there are a few in RadDataForm) or Span will not support child text nodes.

... But one thing at a time!
