### ISSUE TITLE
BottomNavigation component?

### ISSUE THREAD

**Issue by doronnac** [shirakaba/react-nativescript#54]
Hi, my usecase requires a BottomNavigation component
It seems like BottomNavigation is currently not supported, is this correct?

If so, do you have plans to support it?
I'll gladly assist if needed but I'll need some initial guidance.

Thanks

**Comment by shirakaba** [comment]
@doronnac Hiya!

That's right, unfortunately it's not currently supported.

I'm focusing on a big rewrite of React NativeScript right now that means I'll no longer have to hand-write components and plugins. In the next version of RNS, it'll all be automatically-generated, so the whole NativeScript ecosystem will be supported soon after that. I hope to release this sometime during the summer.

I could help with making a BottomNavigation component tomorrow, but instead would a TabView suffice for your needs? BottomNavigation is [just the "improved version" of TabView](https://docs.nativescript.org/ui/components/bottom-navigation). As TabView is already [fully supported](https://react-nativescript.netlify.app/docs/components/tabview) in RNS.

**Comment by doronnac** [comment]
Thanks for your quick response. I'll look into it, maybe it'll be enough

**Comment by shirakaba** [comment]
BottomNavigation is supported in React NativeScript as of v1: https://github.com/shirakaba/react-nativescript/blob/1a11127ed70194cbeb0b45be9dc38b2b9930251c/react-nativescript/src/nativescript-vue-next/runtime/registry.ts#L919
