### ISSUE TITLE
React NativeScript Navigation: No exported member 'NativeStackNavigationProp'

### ISSUE THREAD

**Issue by heritiermwalila** [shirakaba/react-nativescript#69]
`ERROR in components/FirstScreen.tsx:4:10
TS2305: Module '"../../node_modules/react-nativescript-navigation/dist"' has no exported member 'NativeStackNavigationProp'.
    2 | import { RouteProp } from '@react-navigation/core';
    3 | import { Dialogs } from '@nativescript/core';
  > 4 | import { NativeStackNavigationProp } from "react-nativescript-navigation";
      |          ^^^^^^^^^^^^^^^^^^^^^^^^^
    5 | import { MainStackParamList } from "./NavigationParamList";
    6 | 
    7 | type FirstScreenProps = {

ERROR in components/SecondScreen.tsx:3:10
TS2305: Module '"../../node_modules/react-nativescript-navigation/dist"' has no exported member 'NativeStackNavigationProp'.
    1 | import * as React from "react";
    2 | import { RouteProp } from '@react-navigation/core';
  > 3 | import { NativeStackNavigationProp } from "react-nativescript-navigation";
      |          ^^^^^^^^^^^^^^^^^^^^^^^^^
    4 | import { MainStackParamList } from "./NavigationParamList";
    5 | 
    6 | type SecondScreenProps = {
`

**Comment by shirakaba** [comment]
Sorry about this – I’m still waiting for my PR to the RNS template, which fixes this, to be merged.

To fix this, just replace all usages of `NativeStackNavigationProp` with `FrameNavigationProp`.
